In [397]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer

In [398]:
# Especifica la ruta del archivo Parquet
parquet_file_path = 'sample.parquet'

# Lee el archivo Parquet en un DataFrame de Pandas
df = pd.read_parquet(parquet_file_path)

In [399]:
df

,User_id,Time,Rating,Review,Business name,Address,Latitude,Longitude,Category,Avg_rating,Num_of_reviews,Price,State
0,1.182334e+20,2018-06-23 16:48:54.732,1,Poor service overall. Bed sheets have holes fr...,Summit Inn Hotel & Suites,"Summit Inn Hotel & Suites, 1433 N Interstate 3...",29.891854,-97.915345,Hotel,2.1,188,No Price,Texas
1,1.020420e+20,2017-08-07 18:40:49.366,3,"Kinda run down, but the people are fun. Very c...",Acra Manor Resort,"Acra Manor Resort, 487 Old Rte 23, Acra, NY 12405",42.309955,-74.053813,Resort hotel,4.0,68,No Price,New York
2,1.086729e+20,2019-01-18 12:17:06.204,5,Best spa south of the Trinity. Friendly promp...,Luxe Touch,"Luxe Touch, 204 C, S Interstate 35 East Servic...",32.523956,-96.821241,Resort hotel,4.7,78,No Price,Texas
3,1.092079e+20,2016-01-12 04:20:03.117,4,"As someone originally from the Midwest, I was ...",Lee Canyon,"Lee Canyon, 6725 Lee Canyon Rd, Las Vegas, NV ...",36.303702,-115.679633,Ski resort,4.6,1428,No Price,Nevada
4,1.007820e+20,2017-05-17 14:18:21.372,5,Hotel shuttle,Rodeway Inn Near Florida Mall,"Rodeway Inn Near Florida Mall, 6119 S Orange B...",28.468061,-81.396144,Hotel,2.7,238,No Price,Florida
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2813,1.128650e+20,2018-03-07 21:45:06.800,1,None,A1 Value Inn Hernando,"A1 Value Inn Hernando, 2350 N Florida Ave, Her...",28.897244,-82.372984,Hotel,3.3,58,No Price,Florida
2814,1.008935e+20,2020-02-14 13:55:40.401,5,None,Lee Canyon,"Lee Canyon, 6725 Lee Canyon Rd, Las Vegas, NV ...",36.303702,-115.679633,Ski resort,4.6,1428,No Price,Nevada
2815,1.089075e+20,2019-10-08 07:47:08.743,5,None,Lee Canyon,"Lee Canyon, 6725 Lee Canyon Rd, Las Vegas, NV ...",36.303702,-115.679633,Ski resort,4.6,1428,No Price,Nevada
2816,1.171057e+20,2018-08-31 05:58:50.443,1,None,Cowboy Inn,"Cowboy Inn, 3107 N Main St, Fort Worth, TX 76106",32.801603,-97.351239,Indoor lodging,3.1,95,No Price,Texas
2817,1.152103e+20,2020-12-22 01:10:40.503,5,"Love the place, great staff take wonderful car...",Canine Cabana,"Canine Cabana, 9708 Carr Rd, Riverview, FL 33569",27.857669,-82.284642,Pet friendly accommodation,4.8,308,No Price,Florida

In [400]:
# Eliminando columnas irrelevantes
df1 = df.drop(['Time', 'Address', 'Price', 'Rating', 'Num_of_reviews', 'User_id'], axis=1)

In [401]:
df1

,Review,Business name,Latitude,Longitude,Category,Avg_rating,State
0,Poor service overall. Bed sheets have holes fr...,Summit Inn Hotel & Suites,29.891854,-97.915345,Hotel,2.1,Texas
1,"Kinda run down, but the people are fun. Very c...",Acra Manor Resort,42.309955,-74.053813,Resort hotel,4.0,New York
2,Best spa south of the Trinity. Friendly promp...,Luxe Touch,32.523956,-96.821241,Resort hotel,4.7,Texas
3,"As someone originally from the Midwest, I was ...",Lee Canyon,36.303702,-115.679633,Ski resort,4.6,Nevada
4,Hotel shuttle,Rodeway Inn Near Florida Mall,28.468061,-81.396144,Hotel,2.7,Florida
...,...,...,...,...,...,...,...
2813,None,A1 Value Inn Hernando,28.897244,-82.372984,Hotel,3.3,Florida
2814,None,Lee Canyon,36.303702,-115.679633,Ski resort,4.6,Nevada
2815,None,Lee Canyon,36.303702,-115.679633,Ski resort,4.6,Nevada
2816,None,Cowboy Inn,32.801603,-97.351239,Indoor lodging,3.1,Texas
2817,"Love the place, great staff take wonderful car...",Canine Cabana,27.857669,-82.284642,Pet friendly accommodation,4.8,Florida

In [402]:
# ObtÃ©n el Ã­ndice de la columna
column_index = df1.columns.get_loc('Business name')

# Mueve la columna a la izquierda (posiciÃ³n 0)
df1.insert(0, 'Business name', df1.pop('Business name'))

In [403]:
df1

,Business name,Review,Latitude,Longitude,Category,Avg_rating,State
0,Summit Inn Hotel & Suites,Poor service overall. Bed sheets have holes fr...,29.891854,-97.915345,Hotel,2.1,Texas
1,Acra Manor Resort,"Kinda run down, but the people are fun. Very c...",42.309955,-74.053813,Resort hotel,4.0,New York
2,Luxe Touch,Best spa south of the Trinity. Friendly promp...,32.523956,-96.821241,Resort hotel,4.7,Texas
3,Lee Canyon,"As someone originally from the Midwest, I was ...",36.303702,-115.679633,Ski resort,4.6,Nevada
4,Rodeway Inn Near Florida Mall,Hotel shuttle,28.468061,-81.396144,Hotel,2.7,Florida
...,...,...,...,...,...,...,...
2813,A1 Value Inn Hernando,None,28.897244,-82.372984,Hotel,3.3,Florida
2814,Lee Canyon,None,36.303702,-115.679633,Ski resort,4.6,Nevada
2815,Lee Canyon,None,36.303702,-115.679633,Ski resort,4.6,Nevada
2816,Cowboy Inn,None,32.801603,-97.351239,Indoor lodging,3.1,Texas
2817,Canine Cabana,"Love the place, great staff take wonderful car...",27.857669,-82.284642,Pet friendly accommodation,4.8,Florida

In [404]:
# borrando duplicados
data = df1.drop_duplicates()

In [405]:
data

,Business name,Review,Latitude,Longitude,Category,Avg_rating,State
0,Summit Inn Hotel & Suites,Poor service overall. Bed sheets have holes fr...,29.891854,-97.915345,Hotel,2.1,Texas
1,Acra Manor Resort,"Kinda run down, but the people are fun. Very c...",42.309955,-74.053813,Resort hotel,4.0,New York
2,Luxe Touch,Best spa south of the Trinity. Friendly promp...,32.523956,-96.821241,Resort hotel,4.7,Texas
3,Lee Canyon,"As someone originally from the Midwest, I was ...",36.303702,-115.679633,Ski resort,4.6,Nevada
4,Rodeway Inn Near Florida Mall,Hotel shuttle,28.468061,-81.396144,Hotel,2.7,Florida
...,...,...,...,...,...,...,...
2810,Lee Canyon,This place is great on the weekdays its not cr...,36.303702,-115.679633,Ski resort,4.6,Nevada
2811,Jackie Robinson Training Complex,Great Son rise service,27.643010,-80.428259,Hotel,4.4,Florida
2812,5555 Cedar Court Hotel,None,37.531177,-122.006315,Hotel,3.2,California
2813,A1 Value Inn Hernando,None,28.897244,-82.372984,Hotel,3.3,Florida
2817,Canine Cabana,"Love the place, great staff take wonderful car...",27.857669,-82.284642,Pet friendly accommodation,4.8,Florida

In [406]:
# Reseteando el indice 
data.reset_index(drop=True, inplace=True)

In [407]:
# Creando una copia de una variable 
data_1 = data.copy()

In [408]:
data_1

,Business name,Review,Latitude,Longitude,Category,Avg_rating,State
0,Summit Inn Hotel & Suites,Poor service overall. Bed sheets have holes fr...,29.891854,-97.915345,Hotel,2.1,Texas
1,Acra Manor Resort,"Kinda run down, but the people are fun. Very c...",42.309955,-74.053813,Resort hotel,4.0,New York
2,Luxe Touch,Best spa south of the Trinity. Friendly promp...,32.523956,-96.821241,Resort hotel,4.7,Texas
3,Lee Canyon,"As someone originally from the Midwest, I was ...",36.303702,-115.679633,Ski resort,4.6,Nevada
4,Rodeway Inn Near Florida Mall,Hotel shuttle,28.468061,-81.396144,Hotel,2.7,Florida
...,...,...,...,...,...,...,...
2328,Lee Canyon,This place is great on the weekdays its not cr...,36.303702,-115.679633,Ski resort,4.6,Nevada
2329,Jackie Robinson Training Complex,Great Son rise service,27.643010,-80.428259,Hotel,4.4,Florida
2330,5555 Cedar Court Hotel,None,37.531177,-122.006315,Hotel,3.2,California
2331,A1 Value Inn Hernando,None,28.897244,-82.372984,Hotel,3.3,Florida
2332,Canine Cabana,"Love the place, great staff take wonderful car...",27.857669,-82.284642,Pet friendly accommodation,4.8,Florida

In [409]:
# cambiando tipos de datos
data_1['Latitude'] = data_1['Latitude'].astype(str)
data_1['Longitude'] = data_1['Longitude'].astype(str)
data_1['Avg_rating'] = data_1['Avg_rating'].astype(str)

In [410]:
# Combinar los valores de las columnas en una sola columna
data_1['features'] = data_1[['Latitude', 'Longitude', 'Category', 'Avg_rating', 'State']].apply(lambda x: ', '.join(x), axis=1)

data_1.drop(['Latitude', 'Longitude', 'Category', 'Avg_rating', 'State', 'Review'],axis=1,inplace=True)

In [411]:
data_1

,Business name,features
0,Summit Inn Hotel & Suites,"29.891854, -97.915345, Hotel, 2.1, Texas"
1,Acra Manor Resort,"42.3099546, -74.0538134, Resort hotel, 4.0, Ne..."
2,Luxe Touch,"32.5239556, -96.82124119999999, Resort hotel, ..."
3,Lee Canyon,"36.3037018, -115.6796327, Ski resort, 4.6, Nevada"
4,Rodeway Inn Near Florida Mall,"28.468061, -81.39614399999999, Hotel, 2.7, Flo..."
...,...,...
2328,Lee Canyon,"36.3037018, -115.6796327, Ski resort, 4.6, Nevada"
2329,Jackie Robinson Training Complex,"27.6430103, -80.4282588, Hotel, 4.4, Florida"
2330,5555 Cedar Court Hotel,"37.5311769, -122.0063153, Hotel, 3.2, California"
2331,A1 Value Inn Hernando,"28.8972436, -82.3729841, Hotel, 3.3, Florida"
2332,Canine Cabana,"27.8576686, -82.2846419, Pet friendly accommod..."

In [412]:
# Exportar data limpia 
data_1.to_csv('data_hoteles.csv', index=False)

In [414]:
def recomendacion_hoteles(Business_name):
    # cargar los datasets que se van a utilizar para dos dataframes distintos
    data1 = pd.read_csv('data_hoteles.csv')
    
    # Obtener el feature del hospedaje conocido
    features_a_comparar = data1[data1['Business name'] == Business_name]['features'].values[0]

    # Filtrar el DataFrame para hospedajes con el mismo feature (excluyendo el hospedaje conocido)
    df_filtrado = data1[data1['Business name'] != Business_name]
    
    # Inicializar el vectorizador TF-IDF y aplicarlo a los features de los hospedajes
    tfidf_vectorizer = TfidfVectorizer()
    tfidf_matrix = tfidf_vectorizer.fit_transform(df_filtrado['features'])

    # Vectorizar el feature conocido
    vector_feature_conocido = tfidf_vectorizer.transform([features_a_comparar])

    # Calcular la similitud del coseno entre el feature conocido y los feature de los demÃ¡s hospedajes
    similarity_scores = cosine_similarity(vector_feature_conocido, tfidf_matrix)

    # Obtener los Ã­ndices de los 5 hospedajes mÃ¡s similares
    indices_hospedajes_similares = similarity_scores.argsort()[0][-5:][::-1]

    # Obtener los nombres de los hospedajes recomendados utilizando los Ã­ndices
    hospedajes_recomendados = df_filtrado.loc[indices_hospedajes_similares]['Business name'][1:5].tolist()

    # mensaje que indica el negocio del hospedaje original y los negocio de hospedajes recomendados
    mensaje = f"Si te gustÃ³ el hospedaje {Business_name}, tambiÃ©n te pueden gustar:"

    result_dict = {
        'mensaje': mensaje,
        'hospedajes recomendados': hospedajes_recomendados
    }
    
    return result_dict

In [415]:
final = recomendacion_hoteles('5555 Cedar Court Hotel')
print(final)

{'mensaje': 'Si te gustÃ³ el hospedaje 5555 Cedar Court Hotel, tambiÃ©n te pueden gustar:', 'hospedajes recomendados': ['The Spa at Loews Regency San Francisco', 'San Francisco Suites', 'Hot Tub & Sauna In Private Rooms | San Lorezo, CA', 'Galleria Scola']}

In [416]:
# Guardar el DataFrame en formato pickle (.pkl)
result_df.to_pickle('archivo.pkl')

# Leer el DataFrame desde el archivo pickle
data_leido = pd.read_pickle('archivo.pkl')

# Mostrar el DataFrame leÃ­do
print(data_leido)

                 Business name  Luxe Touch
0                   Luxe Touch    1.000000  \
1                   Luxe Touch    1.000000
2                   Luxe Touch    1.000000
3                   Luxe Touch    1.000000
4                   Luxe Touch    1.000000
5                   Luxe Touch    1.000000
6                   Luxe Touch    1.000000
7                   Luxe Touch    1.000000
8                   Luxe Touch    1.000000
9                Travelers Inn    0.399024
10         Park Lane Townhomes    0.398772
11  Beachwood Estates Entrance    0.398772

                                             features
0   32.5239556, -96.82124119999999, Resort hotel, ...
1   32.5239556, -96.82124119999999, Resort hotel, ...
2   32.5239556, -96.82124119999999, Resort hotel, ...
3   32.5239556, -96.82124119999999, Resort hotel, ...
4   32.5239556, -96.82124119999999, Resort hotel, ...
5   32.5239556, -96.82124119999999, Resort hotel, ...
6   32.5239556, -96.82124119999999, Resort hotel, ...
7   32.5239556, -96.82124119999999, Resort hotel, ...
8   32.5239556, -96.82124119999999, Resort hotel, ...
9          32.0765151, -96.4479298, Motel, 2.9, Texas
10  32.876521, -96.87453939999999, Lodging, 2.6, T...
11  32.232791899999995, -96.1394042, Lodging, 3.8,...