# ETL Final de Google Maps y Yelp

Aquí realizaremos el ETL final donde concatenaremos los datos de los 5 estados seleccionados de los datasets de Google Maps y le haremos las transformaciones finales a los datos proporcionados por Yelp

In [1]:
import pandas as pd

Para empezar leemos los datasets de cada estado y los guardamos dentro de una variable

In [10]:
ca_hotels = pd.read_parquet('ca_hotels.parquet')

In [11]:
ca_hotels

,user_id,time,rating,text,business name,address,description,latitude,longitude,category,avg_rating,num_of_reviews,price,state
0,1.089268e+20,2021-06-13 02:27:17.434,4,Great pet friendly place on the American River...,Coloma Cottages,"Coloma Cottages, 5941 New River Rd, Coloma, CA...",None,38.799352,-120.885765,Resort hotel,5.0,48,No Price,None
1,1.089268e+20,2021-06-13 02:27:17.434,4,Great pet friendly place on the American River...,Coloma Cottages,"Coloma Cottages, 5941 New River Rd, Coloma, CA...",None,38.799352,-120.885765,Hotel,5.0,48,No Price,None
2,1.089268e+20,2021-06-13 02:27:17.434,4,Great pet friendly place on the American River...,Coloma Cottages,"Coloma Cottages, 5941 New River Rd, Coloma, CA...",None,38.799352,-120.885765,Indoor lodging,5.0,48,No Price,None
3,1.089268e+20,2021-06-13 02:27:17.434,4,Great pet friendly place on the American River...,Coloma Cottages,"Coloma Cottages, 5941 New River Rd, Coloma, CA...",None,38.799352,-120.885765,Inn,5.0,48,No Price,None
4,1.089268e+20,2021-06-13 02:27:17.434,4,Great pet friendly place on the American River...,Coloma Cottages,"Coloma Cottages, 5941 New River Rd, Coloma, CA...",None,38.799352,-120.885765,Lodge,5.0,48,No Price,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2653,1.112937e+20,2019-04-20 09:25:02.803,5,None,Levyland Estates,"Levyland Estates, 2401 Mountain View Dr, Carls...",None,33.165788,-117.356947,Lodging,4.4,13,No Price,None
2654,1.006838e+20,2016-08-11 17:55:12.019,3,None,Levyland Estates,"Levyland Estates, 2401 Mountain View Dr, Carls...",None,33.165788,-117.356947,Lodging,4.4,13,No Price,None
2655,1.040940e+20,2016-10-30 00:28:34.861,5,None,Levyland Estates,"Levyland Estates, 2401 Mountain View Dr, Carls...",None,33.165788,-117.356947,Lodging,4.4,13,No Price,None
2656,1.040127e+20,2019-06-08 14:57:15.552,3,None,Levyland Estates,"Levyland Estates, 2401 Mountain View Dr, Carls...",None,33.165788,-117.356947,Lodging,4.4,13,No Price,None
2657,1.169914e+20,2019-07-02 07:38:25.558,5,None,Levyland Estates,"Levyland Estates, 2401 Mountain View Dr, Carls...",None,33.165788,-117.356947,Lodging,4.4,13,No Price,None

In [12]:
ca_hotels['state'] = 'California'

In [13]:
ca_hotels

,user_id,time,rating,text,business name,address,description,latitude,longitude,category,avg_rating,num_of_reviews,price,state
0,1.089268e+20,2021-06-13 02:27:17.434,4,Great pet friendly place on the American River...,Coloma Cottages,"Coloma Cottages, 5941 New River Rd, Coloma, CA...",None,38.799352,-120.885765,Resort hotel,5.0,48,No Price,California
1,1.089268e+20,2021-06-13 02:27:17.434,4,Great pet friendly place on the American River...,Coloma Cottages,"Coloma Cottages, 5941 New River Rd, Coloma, CA...",None,38.799352,-120.885765,Hotel,5.0,48,No Price,California
2,1.089268e+20,2021-06-13 02:27:17.434,4,Great pet friendly place on the American River...,Coloma Cottages,"Coloma Cottages, 5941 New River Rd, Coloma, CA...",None,38.799352,-120.885765,Indoor lodging,5.0,48,No Price,California
3,1.089268e+20,2021-06-13 02:27:17.434,4,Great pet friendly place on the American River...,Coloma Cottages,"Coloma Cottages, 5941 New River Rd, Coloma, CA...",None,38.799352,-120.885765,Inn,5.0,48,No Price,California
4,1.089268e+20,2021-06-13 02:27:17.434,4,Great pet friendly place on the American River...,Coloma Cottages,"Coloma Cottages, 5941 New River Rd, Coloma, CA...",None,38.799352,-120.885765,Lodge,5.0,48,No Price,California
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2653,1.112937e+20,2019-04-20 09:25:02.803,5,None,Levyland Estates,"Levyland Estates, 2401 Mountain View Dr, Carls...",None,33.165788,-117.356947,Lodging,4.4,13,No Price,California
2654,1.006838e+20,2016-08-11 17:55:12.019,3,None,Levyland Estates,"Levyland Estates, 2401 Mountain View Dr, Carls...",None,33.165788,-117.356947,Lodging,4.4,13,No Price,California
2655,1.040940e+20,2016-10-30 00:28:34.861,5,None,Levyland Estates,"Levyland Estates, 2401 Mountain View Dr, Carls...",None,33.165788,-117.356947,Lodging,4.4,13,No Price,California
2656,1.040127e+20,2019-06-08 14:57:15.552,3,None,Levyland Estates,"Levyland Estates, 2401 Mountain View Dr, Carls...",None,33.165788,-117.356947,Lodging,4.4,13,No Price,California
2657,1.169914e+20,2019-07-02 07:38:25.558,5,None,Levyland Estates,"Levyland Estates, 2401 Mountain View Dr, Carls...",None,33.165788,-117.356947,Lodging,4.4,13,No Price,California

In [14]:
fl_hotels = pd.read_parquet('fl_hotels.parquet')

In [15]:
fl_hotels['state'] = 'Florida'

In [16]:
nv_hotels = pd.read_parquet('nv_hotels.parquet')

In [17]:
nv_hotels['state'] = 'Nevada'

In [18]:
ny_hotels = pd.read_parquet('ny_hotels.parquet')

In [19]:
ny_hotels['state'] = 'Nueva York'

In [20]:
tx_hotels = pd.read_parquet('tx_hotels.parquet')

In [21]:
tx_hotels['state'] = 'Texas'

In [22]:
tx_hotels

,user_id,time,rating,text,business name,address,description,latitude,longitude,category,avg_rating,num_of_reviews,price,state
0,1.074846e+20,2019-04-23 08:52:42.665,5,Wonderful people! Look forward to getting to k...,Pine Tree Masonic Lodge,"Pine Tree Masonic Lodge, 2709 Pine Tree Rd, Lo...",None,32.534913,-94.808631,Lodge,4.3,8,No Price,Texas
1,1.112976e+20,2019-12-02 03:43:52.124,4,For the more mature crowd,Pine Tree Masonic Lodge,"Pine Tree Masonic Lodge, 2709 Pine Tree Rd, Lo...",None,32.534913,-94.808631,Lodge,4.3,8,No Price,Texas
2,1.110295e+20,2021-01-07 04:53:47.209,4,(Translated by Google) A O K\n\n(Original)\nA ...,Pine Tree Masonic Lodge,"Pine Tree Masonic Lodge, 2709 Pine Tree Rd, Lo...",None,32.534913,-94.808631,Lodge,4.3,8,No Price,Texas
3,1.146522e+20,2016-12-16 21:34:40.848,5,None,Pine Tree Masonic Lodge,"Pine Tree Masonic Lodge, 2709 Pine Tree Rd, Lo...",None,32.534913,-94.808631,Lodge,4.3,8,No Price,Texas
4,1.089870e+20,2019-05-16 00:50:52.433,5,None,Pine Tree Masonic Lodge,"Pine Tree Masonic Lodge, 2709 Pine Tree Rd, Lo...",None,32.534913,-94.808631,Lodge,4.3,8,No Price,Texas
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9594,1.091356e+20,2018-09-06 00:06:08.768,3,None,The Guild Music District | Red River St,"The Guild Music District | Red River St, 901 R...",Hip quarters with kitchens in a retro music-in...,30.269618,-97.735606,Hotel,4.4,78,No Price,Texas
9595,1.037933e+20,2018-10-29 12:59:50.424,5,None,The Guild Music District | Red River St,"The Guild Music District | Red River St, 901 R...",Hip quarters with kitchens in a retro music-in...,30.269618,-97.735606,Hotel,4.4,78,No Price,Texas
9596,1.170984e+20,2019-09-19 16:53:59.564,5,None,The Guild Music District | Red River St,"The Guild Music District | Red River St, 901 R...",Hip quarters with kitchens in a retro music-in...,30.269618,-97.735606,Hotel,4.4,78,No Price,Texas
9597,1.121368e+20,2019-08-14 13:01:16.619,5,None,The Guild Music District | Red River St,"The Guild Music District | Red River St, 901 R...",Hip quarters with kitchens in a retro music-in...,30.269618,-97.735606,Hotel,4.4,78,No Price,Texas
9598,1.102373e+20,2019-02-17 16:58:20.440,5,None,The Guild Music District | Red River St,"The Guild Music District | Red River St, 901 R...",Hip quarters with kitchens in a retro music-in...,30.269618,-97.735606,Hotel,4.4,78,No Price,Texas

Ahora concatenamos todos los dataframes en uno solo

In [28]:
df = pd.concat([ca_hotels, fl_hotels, nv_hotels, ny_hotels, tx_hotels], axis=0, ignore_index=True)

In [29]:
df

,user_id,time,rating,text,business name,address,description,latitude,longitude,category,avg_rating,num_of_reviews,price,state
0,1.089268e+20,2021-06-13 02:27:17.434,4,Great pet friendly place on the American River...,Coloma Cottages,"Coloma Cottages, 5941 New River Rd, Coloma, CA...",None,38.799352,-120.885765,Resort hotel,5.0,48,No Price,California
1,1.089268e+20,2021-06-13 02:27:17.434,4,Great pet friendly place on the American River...,Coloma Cottages,"Coloma Cottages, 5941 New River Rd, Coloma, CA...",None,38.799352,-120.885765,Hotel,5.0,48,No Price,California
2,1.089268e+20,2021-06-13 02:27:17.434,4,Great pet friendly place on the American River...,Coloma Cottages,"Coloma Cottages, 5941 New River Rd, Coloma, CA...",None,38.799352,-120.885765,Indoor lodging,5.0,48,No Price,California
3,1.089268e+20,2021-06-13 02:27:17.434,4,Great pet friendly place on the American River...,Coloma Cottages,"Coloma Cottages, 5941 New River Rd, Coloma, CA...",None,38.799352,-120.885765,Inn,5.0,48,No Price,California
4,1.089268e+20,2021-06-13 02:27:17.434,4,Great pet friendly place on the American River...,Coloma Cottages,"Coloma Cottages, 5941 New River Rd, Coloma, CA...",None,38.799352,-120.885765,Lodge,5.0,48,No Price,California
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28178,1.091356e+20,2018-09-06 00:06:08.768,3,None,The Guild Music District | Red River St,"The Guild Music District | Red River St, 901 R...",Hip quarters with kitchens in a retro music-in...,30.269618,-97.735606,Hotel,4.4,78,No Price,Texas
28179,1.037933e+20,2018-10-29 12:59:50.424,5,None,The Guild Music District | Red River St,"The Guild Music District | Red River St, 901 R...",Hip quarters with kitchens in a retro music-in...,30.269618,-97.735606,Hotel,4.4,78,No Price,Texas
28180,1.170984e+20,2019-09-19 16:53:59.564,5,None,The Guild Music District | Red River St,"The Guild Music District | Red River St, 901 R...",Hip quarters with kitchens in a retro music-in...,30.269618,-97.735606,Hotel,4.4,78,No Price,Texas
28181,1.121368e+20,2019-08-14 13:01:16.619,5,None,The Guild Music District | Red River St,"The Guild Music District | Red River St, 901 R...",Hip quarters with kitchens in a retro music-in...,30.269618,-97.735606,Hotel,4.4,78,No Price,Texas
28182,1.102373e+20,2019-02-17 16:58:20.440,5,None,The Guild Music District | Red River St,"The Guild Music District | Red River St, 901 R...",Hip quarters with kitchens in a retro music-in...,30.269618,-97.735606,Hotel,4.4,78,No Price,Texas

In [30]:
google_maps = df

Eliminamos columnas que no son de nuestro interés

In [31]:
google_maps.drop(['text', 'address', 'description', 'price'], axis=1, inplace=True)

In [32]:
google_maps

,user_id,time,rating,business name,latitude,longitude,category,avg_rating,num_of_reviews,state
0,1.089268e+20,2021-06-13 02:27:17.434,4,Coloma Cottages,38.799352,-120.885765,Resort hotel,5.0,48,California
1,1.089268e+20,2021-06-13 02:27:17.434,4,Coloma Cottages,38.799352,-120.885765,Hotel,5.0,48,California
2,1.089268e+20,2021-06-13 02:27:17.434,4,Coloma Cottages,38.799352,-120.885765,Indoor lodging,5.0,48,California
3,1.089268e+20,2021-06-13 02:27:17.434,4,Coloma Cottages,38.799352,-120.885765,Inn,5.0,48,California
4,1.089268e+20,2021-06-13 02:27:17.434,4,Coloma Cottages,38.799352,-120.885765,Lodge,5.0,48,California
...,...,...,...,...,...,...,...,...,...,...
28178,1.091356e+20,2018-09-06 00:06:08.768,3,The Guild Music District | Red River St,30.269618,-97.735606,Hotel,4.4,78,Texas
28179,1.037933e+20,2018-10-29 12:59:50.424,5,The Guild Music District | Red River St,30.269618,-97.735606,Hotel,4.4,78,Texas
28180,1.170984e+20,2019-09-19 16:53:59.564,5,The Guild Music District | Red River St,30.269618,-97.735606,Hotel,4.4,78,Texas
28181,1.121368e+20,2019-08-14 13:01:16.619,5,The Guild Music District | Red River St,30.269618,-97.735606,Hotel,4.4,78,Texas
28182,1.102373e+20,2019-02-17 16:58:20.440,5,The Guild Music District | Red River St,30.269618,-97.735606,Hotel,4.4,78,Texas

Realizaremos una transformación de la columna 'time' para extraer solamente el mes y el año:

In [33]:
google_maps['time'] = google_maps['time'].astype(str)

In [34]:
google_maps

,user_id,time,rating,business name,latitude,longitude,category,avg_rating,num_of_reviews,state
0,1.089268e+20,2021-06-13 02:27:17.434,4,Coloma Cottages,38.799352,-120.885765,Resort hotel,5.0,48,California
1,1.089268e+20,2021-06-13 02:27:17.434,4,Coloma Cottages,38.799352,-120.885765,Hotel,5.0,48,California
2,1.089268e+20,2021-06-13 02:27:17.434,4,Coloma Cottages,38.799352,-120.885765,Indoor lodging,5.0,48,California
3,1.089268e+20,2021-06-13 02:27:17.434,4,Coloma Cottages,38.799352,-120.885765,Inn,5.0,48,California
4,1.089268e+20,2021-06-13 02:27:17.434,4,Coloma Cottages,38.799352,-120.885765,Lodge,5.0,48,California
...,...,...,...,...,...,...,...,...,...,...
28178,1.091356e+20,2018-09-06 00:06:08.768,3,The Guild Music District | Red River St,30.269618,-97.735606,Hotel,4.4,78,Texas
28179,1.037933e+20,2018-10-29 12:59:50.424,5,The Guild Music District | Red River St,30.269618,-97.735606,Hotel,4.4,78,Texas
28180,1.170984e+20,2019-09-19 16:53:59.564,5,The Guild Music District | Red River St,30.269618,-97.735606,Hotel,4.4,78,Texas
28181,1.121368e+20,2019-08-14 13:01:16.619,5,The Guild Music District | Red River St,30.269618,-97.735606,Hotel,4.4,78,Texas
28182,1.102373e+20,2019-02-17 16:58:20.440,5,The Guild Music District | Red River St,30.269618,-97.735606,Hotel,4.4,78,Texas

In [35]:
google_maps['year'] = google_maps['time'].apply(lambda x: x[:4])
google_maps['month'] = google_maps['time'].apply(lambda x: x[5:7])

In [36]:
google_maps

,user_id,time,rating,business name,latitude,longitude,category,avg_rating,num_of_reviews,state,year,month
0,1.089268e+20,2021-06-13 02:27:17.434,4,Coloma Cottages,38.799352,-120.885765,Resort hotel,5.0,48,California,2021,06
1,1.089268e+20,2021-06-13 02:27:17.434,4,Coloma Cottages,38.799352,-120.885765,Hotel,5.0,48,California,2021,06
2,1.089268e+20,2021-06-13 02:27:17.434,4,Coloma Cottages,38.799352,-120.885765,Indoor lodging,5.0,48,California,2021,06
3,1.089268e+20,2021-06-13 02:27:17.434,4,Coloma Cottages,38.799352,-120.885765,Inn,5.0,48,California,2021,06
4,1.089268e+20,2021-06-13 02:27:17.434,4,Coloma Cottages,38.799352,-120.885765,Lodge,5.0,48,California,2021,06
...,...,...,...,...,...,...,...,...,...,...,...,...
28178,1.091356e+20,2018-09-06 00:06:08.768,3,The Guild Music District | Red River St,30.269618,-97.735606,Hotel,4.4,78,Texas,2018,09
28179,1.037933e+20,2018-10-29 12:59:50.424,5,The Guild Music District | Red River St,30.269618,-97.735606,Hotel,4.4,78,Texas,2018,10
28180,1.170984e+20,2019-09-19 16:53:59.564,5,The Guild Music District | Red River St,30.269618,-97.735606,Hotel,4.4,78,Texas,2019,09
28181,1.121368e+20,2019-08-14 13:01:16.619,5,The Guild Music District | Red River St,30.269618,-97.735606,Hotel,4.4,78,Texas,2019,08
28182,1.102373e+20,2019-02-17 16:58:20.440,5,The Guild Music District | Red River St,30.269618,-97.735606,Hotel,4.4,78,Texas,2019,02

Finalmente eliminamos la columna 'time' y convertimos las nuevas columnas 'month' y 'year' a tipo entero

In [37]:
google_maps.drop('time', axis=1, inplace=True)

In [38]:
google_maps

,user_id,rating,business name,latitude,longitude,category,avg_rating,num_of_reviews,state,year,month
0,1.089268e+20,4,Coloma Cottages,38.799352,-120.885765,Resort hotel,5.0,48,California,2021,06
1,1.089268e+20,4,Coloma Cottages,38.799352,-120.885765,Hotel,5.0,48,California,2021,06
2,1.089268e+20,4,Coloma Cottages,38.799352,-120.885765,Indoor lodging,5.0,48,California,2021,06
3,1.089268e+20,4,Coloma Cottages,38.799352,-120.885765,Inn,5.0,48,California,2021,06
4,1.089268e+20,4,Coloma Cottages,38.799352,-120.885765,Lodge,5.0,48,California,2021,06
...,...,...,...,...,...,...,...,...,...,...,...
28178,1.091356e+20,3,The Guild Music District | Red River St,30.269618,-97.735606,Hotel,4.4,78,Texas,2018,09
28179,1.037933e+20,5,The Guild Music District | Red River St,30.269618,-97.735606,Hotel,4.4,78,Texas,2018,10
28180,1.170984e+20,5,The Guild Music District | Red River St,30.269618,-97.735606,Hotel,4.4,78,Texas,2019,09
28181,1.121368e+20,5,The Guild Music District | Red River St,30.269618,-97.735606,Hotel,4.4,78,Texas,2019,08
28182,1.102373e+20,5,The Guild Music District | Red River St,30.269618,-97.735606,Hotel,4.4,78,Texas,2019,02

In [39]:
google_maps['year'] = google_maps['year'].astype(int)
google_maps['month'] = google_maps['month'].astype(int)

Guardamos el dataset

In [40]:
google_maps.to_parquet('Google_Maps.parquet', index=False)

Ahora importamos el dataset de Yelp (luego de haberle realizado transformaciones) y lo guardamos en una variable

In [32]:
review = pd.read_parquet('review.parquet')

In [33]:
review

,business_id,name,city,state,latitude,longitude,categories,review_id,user_id,stars,date,sent_analysis
0,-aeZuatjCDMV1X4gCTz9Ug,David Thomas Trailways,Philadelphia,FL,40.106409,-74.973937,"Buses, Transportation, Bus Tours, Hotels & Tra...",Bj6g6pCM5dBBlNO2EwRP6w,NePHFwSt7Hvuc9tbQ6S-aQ,5.0,2014-08-21 14:12:08,2
1,-aeZuatjCDMV1X4gCTz9Ug,David Thomas Trailways,Philadelphia,FL,40.106409,-74.973937,"Buses, Transportation, Bus Tours, Hotels & Tra...",uzJfKuY4kNjpIHQJLHg8Gg,eLuM7MT4twNmdAPF8Xxi7Q,5.0,2020-06-01 15:11:31,2
2,-aeZuatjCDMV1X4gCTz9Ug,David Thomas Trailways,Philadelphia,FL,40.106409,-74.973937,"Buses, Transportation, Bus Tours, Hotels & Tra...",CSy6BEXqqr-hJfwrUhK3dQ,yFFa4AIe7zM3o9pEzVIB2Q,1.0,2016-07-25 02:50:46,0
3,-aeZuatjCDMV1X4gCTz9Ug,David Thomas Trailways,Philadelphia,FL,40.106409,-74.973937,"Buses, Transportation, Bus Tours, Hotels & Tra...",FQnqH3UDL01DhFPV03ADPw,VCxY2F6Q4ADlaRLTD3m6rA,5.0,2019-05-06 20:57:24,2
4,-aeZuatjCDMV1X4gCTz9Ug,David Thomas Trailways,Philadelphia,FL,40.106409,-74.973937,"Buses, Transportation, Bus Tours, Hotels & Tra...",a5u1u1Or4-qmhEQYKzgLZQ,udmsyG7J4Hgl954xVL1hjQ,5.0,2021-10-26 21:09:44,2
...,...,...,...,...,...,...,...,...,...,...,...,...
82920,JkF0um3dxe-cOBYeergOhQ,St Petersburg Carriages,St. Petersburg,NV,27.775253,-82.632121,"Tours, Hotels & Travel, Event Planning & Servi...",FZPZOACgGia2dONvLXSS7w,qjfMBIZpQT9DDtw_BWCopQ,4.0,2016-03-04 01:48:59,2
82921,JkF0um3dxe-cOBYeergOhQ,St Petersburg Carriages,St. Petersburg,NV,27.775253,-82.632121,"Tours, Hotels & Travel, Event Planning & Servi...",TBTrB5u5H1CUlUI-GHuu9Q,NA9fkvlaPKoNwbk97eO6bA,1.0,2016-02-15 20:22:33,1
82922,JkF0um3dxe-cOBYeergOhQ,St Petersburg Carriages,St. Petersburg,NV,27.775253,-82.632121,"Tours, Hotels & Travel, Event Planning & Servi...",_iDSYEvWhjTcw02Rt4WM_A,pCMX9AXtoXLvIldAuLGS3Q,1.0,2017-08-25 13:04:27,0
82923,JkF0um3dxe-cOBYeergOhQ,St Petersburg Carriages,St. Petersburg,NV,27.775253,-82.632121,"Tours, Hotels & Travel, Event Planning & Servi...",ZRpLZsP7SDIIV3csMdk4gw,SWJtXwHLpl-6CXPPiTCNQQ,5.0,2018-02-18 02:18:39,2
82924,JkF0um3dxe-cOBYeergOhQ,St Petersburg Carriages,St. Petersburg,NV,27.775253,-82.632121,"Tours, Hotels & Travel, Event Planning & Servi...",qQ6z9DOSBSqf5IWBThgQJw,mMvf6w_I5AFJH0EQMb-OIw,5.0,2016-04-10 15:24:53,2

Eliminamos columnas que no son de nuestro interés

In [34]:
review.drop(['business_id', 'city', 'state', 'latitude', 'longitude', 'user_id'], axis=1, inplace=True)

In [35]:
review

,name,categories,review_id,stars,date,sent_analysis
0,David Thomas Trailways,"Buses, Transportation, Bus Tours, Hotels & Tra...",Bj6g6pCM5dBBlNO2EwRP6w,5.0,2014-08-21 14:12:08,2
1,David Thomas Trailways,"Buses, Transportation, Bus Tours, Hotels & Tra...",uzJfKuY4kNjpIHQJLHg8Gg,5.0,2020-06-01 15:11:31,2
2,David Thomas Trailways,"Buses, Transportation, Bus Tours, Hotels & Tra...",CSy6BEXqqr-hJfwrUhK3dQ,1.0,2016-07-25 02:50:46,0
3,David Thomas Trailways,"Buses, Transportation, Bus Tours, Hotels & Tra...",FQnqH3UDL01DhFPV03ADPw,5.0,2019-05-06 20:57:24,2
4,David Thomas Trailways,"Buses, Transportation, Bus Tours, Hotels & Tra...",a5u1u1Or4-qmhEQYKzgLZQ,5.0,2021-10-26 21:09:44,2
...,...,...,...,...,...,...
82920,St Petersburg Carriages,"Tours, Hotels & Travel, Event Planning & Servi...",FZPZOACgGia2dONvLXSS7w,4.0,2016-03-04 01:48:59,2
82921,St Petersburg Carriages,"Tours, Hotels & Travel, Event Planning & Servi...",TBTrB5u5H1CUlUI-GHuu9Q,1.0,2016-02-15 20:22:33,1
82922,St Petersburg Carriages,"Tours, Hotels & Travel, Event Planning & Servi...",_iDSYEvWhjTcw02Rt4WM_A,1.0,2017-08-25 13:04:27,0
82923,St Petersburg Carriages,"Tours, Hotels & Travel, Event Planning & Servi...",ZRpLZsP7SDIIV3csMdk4gw,5.0,2018-02-18 02:18:39,2
82924,St Petersburg Carriages,"Tours, Hotels & Travel, Event Planning & Servi...",qQ6z9DOSBSqf5IWBThgQJw,5.0,2016-04-10 15:24:53,2

Separamos las categorías

In [36]:
reviews_yelp = review.assign(categories=review['categories'].str.split(', ')).explode('categories').reset_index(drop=True)

In [37]:
reviews_yelp

,name,categories,review_id,stars,date,sent_analysis
0,David Thomas Trailways,Buses,Bj6g6pCM5dBBlNO2EwRP6w,5.0,2014-08-21 14:12:08,2
1,David Thomas Trailways,Transportation,Bj6g6pCM5dBBlNO2EwRP6w,5.0,2014-08-21 14:12:08,2
2,David Thomas Trailways,Bus Tours,Bj6g6pCM5dBBlNO2EwRP6w,5.0,2014-08-21 14:12:08,2
3,David Thomas Trailways,Hotels & Travel,Bj6g6pCM5dBBlNO2EwRP6w,5.0,2014-08-21 14:12:08,2
4,David Thomas Trailways,Travel Agents,Bj6g6pCM5dBBlNO2EwRP6w,5.0,2014-08-21 14:12:08,2
...,...,...,...,...,...,...
445156,St Petersburg Carriages,Tours,qQ6z9DOSBSqf5IWBThgQJw,5.0,2016-04-10 15:24:53,2
445157,St Petersburg Carriages,Hotels & Travel,qQ6z9DOSBSqf5IWBThgQJw,5.0,2016-04-10 15:24:53,2
445158,St Petersburg Carriages,Event Planning & Services,qQ6z9DOSBSqf5IWBThgQJw,5.0,2016-04-10 15:24:53,2
445159,St Petersburg Carriages,Venues & Event Spaces,qQ6z9DOSBSqf5IWBThgQJw,5.0,2016-04-10 15:24:53,2
445160,St Petersburg Carriages,Local Flavor,qQ6z9DOSBSqf5IWBThgQJw,5.0,2016-04-10 15:24:53,2

Realizamos el mismo procedimiento anterior para transformar la columna 'date' y extraer solamente el mes y el año

In [38]:
reviews_yelp['year'] = reviews_yelp['date'].apply(lambda x: x[:4])
reviews_yelp['month'] = reviews_yelp['date'].apply(lambda x: x[5:7])

In [39]:
reviews_yelp

,name,categories,review_id,stars,date,sent_analysis,year,month
0,David Thomas Trailways,Buses,Bj6g6pCM5dBBlNO2EwRP6w,5.0,2014-08-21 14:12:08,2,2014,08
1,David Thomas Trailways,Transportation,Bj6g6pCM5dBBlNO2EwRP6w,5.0,2014-08-21 14:12:08,2,2014,08
2,David Thomas Trailways,Bus Tours,Bj6g6pCM5dBBlNO2EwRP6w,5.0,2014-08-21 14:12:08,2,2014,08
3,David Thomas Trailways,Hotels & Travel,Bj6g6pCM5dBBlNO2EwRP6w,5.0,2014-08-21 14:12:08,2,2014,08
4,David Thomas Trailways,Travel Agents,Bj6g6pCM5dBBlNO2EwRP6w,5.0,2014-08-21 14:12:08,2,2014,08
...,...,...,...,...,...,...,...,...
445156,St Petersburg Carriages,Tours,qQ6z9DOSBSqf5IWBThgQJw,5.0,2016-04-10 15:24:53,2,2016,04
445157,St Petersburg Carriages,Hotels & Travel,qQ6z9DOSBSqf5IWBThgQJw,5.0,2016-04-10 15:24:53,2,2016,04
445158,St Petersburg Carriages,Event Planning & Services,qQ6z9DOSBSqf5IWBThgQJw,5.0,2016-04-10 15:24:53,2,2016,04
445159,St Petersburg Carriages,Venues & Event Spaces,qQ6z9DOSBSqf5IWBThgQJw,5.0,2016-04-10 15:24:53,2,2016,04
445160,St Petersburg Carriages,Local Flavor,qQ6z9DOSBSqf5IWBThgQJw,5.0,2016-04-10 15:24:53,2,2016,04

In [40]:
reviews_yelp.drop('date', axis=1, inplace=True)

In [41]:
reviews_yelp['year'] = reviews_yelp['year'].astype(int)
reviews_yelp['month'] = reviews_yelp['month'].astype(int)

In [42]:
reviews_yelp

,name,categories,review_id,stars,sent_analysis,year,month
0,David Thomas Trailways,Buses,Bj6g6pCM5dBBlNO2EwRP6w,5.0,2,2014,8
1,David Thomas Trailways,Transportation,Bj6g6pCM5dBBlNO2EwRP6w,5.0,2,2014,8
2,David Thomas Trailways,Bus Tours,Bj6g6pCM5dBBlNO2EwRP6w,5.0,2,2014,8
3,David Thomas Trailways,Hotels & Travel,Bj6g6pCM5dBBlNO2EwRP6w,5.0,2,2014,8
4,David Thomas Trailways,Travel Agents,Bj6g6pCM5dBBlNO2EwRP6w,5.0,2,2014,8
...,...,...,...,...,...,...,...
445156,St Petersburg Carriages,Tours,qQ6z9DOSBSqf5IWBThgQJw,5.0,2,2016,4
445157,St Petersburg Carriages,Hotels & Travel,qQ6z9DOSBSqf5IWBThgQJw,5.0,2,2016,4
445158,St Petersburg Carriages,Event Planning & Services,qQ6z9DOSBSqf5IWBThgQJw,5.0,2,2016,4
445159,St Petersburg Carriages,Venues & Event Spaces,qQ6z9DOSBSqf5IWBThgQJw,5.0,2,2016,4
445160,St Petersburg Carriages,Local Flavor,qQ6z9DOSBSqf5IWBThgQJw,5.0,2,2016,4

Guardamos en formato Parquet

In [43]:
reviews_yelp.to_parquet('Reviews_Yelp.parquet', index=False)